#:schema node_modules/wrangler/config-schema.json
name = "img"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./public", binding = "ASSETS" }

observability= { enabled = true }

vars = { CF_CACHE_TTL=1000, S3_CDN_URL="r2.hvg.hu", S3_CDN_DIR="/uploads/" }

kv_namespaces = [
    { binding = "IMG_KV", id = "eb17d6e8a8aa4e5384bb38b5241a6de7",   preview_id = "eb17d6e8a8aa4e5384bb38b5241a6de7"}
]

r2_buckets = [
    { binding = "IMG_BUCKET", bucket_name  = "img",   preview_bucket_name = "img"}
]

routes = [
    { pattern = "img.hvg.hu", custom_domain = true }
]

version_metadata = { binding = "CF_VERSION_METADATA" }


[env.test_staging]

vars = { CF_CACHE_TTL=1000, S3_CDN_URL="r2.test-hvg.hu", S3_CDN_DIR="/uploads/" }

kv_namespaces = [
    { binding = "IMG_KV", id = "678045e22e7e4215999c86774023fb3b",   preview_id = "678045e22e7e4215999c86774023fb3b"}
#   { binding = "IMG_KV", id = "678045e22e7e4215999c86774023fb3b",   preview_id = "9f6d5f1bc6364a0a84401f4e1b213e34"}
]

r2_buckets = [
    { binding = "IMG_BUCKET", bucket_name  = "img-dev",   preview_bucket_name = "img-dev"}
]

routes = [
    { pattern = "img.test-hvg.hu", custom_domain = true },
    { pattern = "img.staging-hvg.hu", custom_domain = true }
]

version_metadata = { binding = "CF_VERSION_METADATA" }
