name: CICD

on:
  push:
  pull_request:
  workflow_dispatch: #kezi inditas

env:
  WRANGLER_VERSION: "4.5.0"
  CLOUDFLARE_WORKER_ENV: "test_staging"
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
jobs:
  check:
    name: Check
    runs-on: [ubuntu-latest]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@master
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - name: EditorConfig Check
        run: editorconfig-checker
      - name: Json / Yaml Validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.4.0
        with:
          comment: "true"
          allow_multiple_documents: "true"
          exclude_file: ".jsonyamlex"
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: PS-Check
        uses: SleepySysadmin/github-action-pscheck@master
  deploy:
    name: Deploy
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [check]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          environment: ${{ env.CLOUDFLARE_WORKER_ENV }}
          wranglerVersion: ${{ env.WRANGLER_VERSION }}
